// campaign-engine.js — TENET5 Email Generation Engine
// Generates personalized accountability emails for each recipient type
// All evidence facts trace to official Government of Canada publications

var BASE_URL = 'https://tenet-5.github.io/';

var CLOSING_FOOTER = '\n\n\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\nThis analysis was generated by TENET5 OSINT, an open-source intelligence system that cross-references 7 million records from official Canadian government databases. Every statistic traces to a published government source.\n\nEvidence and methodology: https://tenet-5.github.io/about.html\nFull evidence index (32 verified files): https://tenet-5.github.io/evidence-index.html\nLegal framework: https://tenet-5.github.io/legal.html\n\nTENET5 \u2014 Powered by LIRIL AI\ntenet-5.github.io\n\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500';

function generateCampaignEmail(contact, allFlaggedPeople) {
  switch (contact.category) {
    case 'senate':        return generateSenateEmail(contact, allFlaggedPeople);
    case 'media':         return generateMediaEmail(contact, allFlaggedPeople);
    case 'thinkTank':     return generateThinkTankEmail(contact, allFlaggedPeople);
    case 'premier':       return generatePremierEmail(contact, allFlaggedPeople);
    case 'military':      return generateMilitaryEmail(contact, allFlaggedPeople);
    case 'court':         return generateCourtEmail(contact, allFlaggedPeople);
    case 'lawEnforcement': return generateLawEnforcementEmail(contact, allFlaggedPeople);
    case 'mp':            return generateMPEmail(contact, allFlaggedPeople);
    case 'courthouse':    return generateCourthouseEmail(contact, allFlaggedPeople);
    default:              return generateGenericEmail(contact);
  }
}

// ============================================================
// SENATE EMAIL
// ============================================================
function generateSenateEmail(contact, allFlaggedPeople) {
  var subject, body;
  var senatorFlagged = allFlaggedPeople
    ? allFlaggedPeople.filter(function(c) { return c.category === 'senate' && c.name !== contact.name; })
    : [];

  if (contact.flagScore === 0) {
    // Clean senator — full accountability brief
    subject = 'Senate Accountability Brief \u2014 Evidence for s.122 Criminal Code Referral | ' + contact.name;
    body = 'Dear ' + contact.name + ',\n\n' +
      'As a Senator, you are responsible under Senate Rule 1 and Rule 2 to serve the public interest and uphold the public trust. This briefing presents documented evidence of accountability failures that merit Senate action.\n\n' +
      'This analysis was generated by TENET5 OSINT, an automated intelligence system that cross-references 7 million records from official Canadian government databases.\n\n' +
      '1. ETHICS ENFORCEMENT FAILURE\n' +
      'PM Trudeau was found in contravention of the Conflict of Interest Act twice (2017: Aga Khan; 2019: SNC-Lavalin). PM Carney has declared 100+ recusals; his former company Brookfield pitched a $50B fund while he advised the previous PM; 95% of his portfolio is not covered by his ethics screen. Nine ministers have violated the Act; the combined penalty across all cases is approximately $9,391 (one repayment). Zero fines. Zero criminal referrals. Source: Ethics Commissioner published reports.\n\n' +
      '2. SDTC "GREEN SLUSH FUND"\n' +
      '186 documented conflicts of interest within Sustainable Development Technology Canada. Approximately $400M in questioned grants. Board Chair Verschuren voted on grants to her own company NRStor, violating ss.6(1) and 21 of the Conflict of Interest Act. The government was found in contempt of Parliament for refusing to surrender documents. Source: Auditor General Report 2024, Ethics Commissioner.\n\n' +
      '3. LOBBYING CONCENTRATION\n' +
      '359,251 registered lobbying communications from the Commissioner of Lobbying raw CSV data. The PMO received 20,383 contacts. CIJA alone: 2,156 communications at 539 contacts per organization \u2014 22x the rate of China-linked organizations. January 2026 Lobbying Act reforms created an 8-hour threshold not yet being enforced. Source: Commissioner of Lobbying raw CSV (lobbycanada.gc.ca).\n\n' +
      '4. ARMS EXPORT CONTRADICTIONS\n' +
      '$229M+ in Canadian arms flowed to Israel despite an announced "pause." $18.9M shipped after the pause was announced; $37.2M in new permits issued. A Crown corporation signed a $78.8M contract weeks after blocking the same company. 12 CRA charity revocations for funnelling funds to military operations abroad. Source: Global Affairs Canada, Auditor General.\n\n' +
      '5. FOREIGN INTERFERENCE\n' +
      'The NSICOP 2024 report found that parliamentarians from multiple parties are "wittingly" assisting foreign governments. CPC leadership races were infiltrated. Bill C-70\'s foreign agent registry was delayed by the election and enforcement remains inconsistent. Source: NSICOP Report 2024.\n\n' +
      '6. MEDICAL ASSISTANCE IN DYING (MAID)\n' +
      'Canada has the highest per-capita MAID deaths of any country with MAID legislation. 76,475+ cumulative deaths. 16,499 in 2024 alone \u2014 5.1% of all Canadian deaths. Bill C-7 removed the 10-day reflection period and allowed MAID for mental illness alone. Source: Health Canada Annual Report on MAID.\n\n' +
      '7. PROCUREMENT FAILURES\n' +
      'ArriveCAN: $60M for an app estimated at $250K. GC Strategies (2 employees) received $20.9M in contracts. Source: Auditor General Report 2024.\n\n' +
      '8. OFFSHORE FINANCIAL ROUTING\n' +
      'Eight major document leaks (LuxLeaks 2014 through Cyprus Confidential 2023) exposed 268,488 offshore entities. 912 Canadian entities in Panama Papers alone. CRA identified $76M in unpaid taxes \u2014 zero confirmed collected. PM holds $6.8M in Brookfield options while cutting FINTRAC budget 12% (47 analyst positions). Source: ICIJ Offshore Leaks Database, CRA, FINTRAC Annual Report 2024.\n\n' +
      '9. CAF/CFNIS OVERSIGHT\n' +
      'CFNIS reports to the same chain of command it investigates. MPCC has repeatedly found investigations exceeded the 12-month standard (some ran 3\u20135 years). The Provost Marshal was accused of obstruction. LCol LeBlanc cleared Gen Vance despite allegations. Source: MPCC Annual Reports, Federal Court.\n\n' +
      'RECOMMENDED SENATE ACTION:\n\n' +
      '1. Refer Ethics Commissioner findings to RCMP under Criminal Code s.122 (Breach of Trust by Public Officer \u2014 up to 5 years imprisonment)\n' +
      '2. Senate study on Conflict of Interest Act reform: 10-year post-employment cooling period, full PM divestiture, criminal penalties\n' +
      '3. Senate study on independent CFNIS oversight: remove from chain of command, give MPCC binding investigative power\n' +
      '4. Senate study on lobbying concentration patterns using Commissioner of Lobbying raw data\n' +
      '5. Senate review of Bill C-70 foreign agent registry enforcement consistency\n' +
      '6. Senate study on FINTRAC defunding: demand restoration of 47 analyst positions and offshore tax enforcement\n\n' +
      'EVIDENCE:\n' +
      '  Full investigation findings: ' + BASE_URL + 'findings.html\n' +
      '  Legal framework: ' + BASE_URL + 'legal.html\n' +
      '  Evidence index (32 verified files): ' + BASE_URL + 'evidence-index.html\n' +
      '  Lobbying data: ' + BASE_URL + 'sector-lobbying.html\n' +
      '  Arms pipeline: ' + BASE_URL + 'arms-pipeline.html\n' +
      '  Carney conflicts: ' + BASE_URL + 'carney-conflicts.html\n\n' +
      'Every statistic sourced from official Government of Canada publications. Corrections policy: ' + BASE_URL + 'about.html' +
      CLOSING_FOOTER;
  } else {
    // Flagged senator — show colleagues' records (not their own)
    subject = 'Accountability Brief: Documented Ethics Violations by Your Senate Colleagues | ' + contact.name;
    body = 'Dear ' + contact.name + ',\n\n' +
      'As a Senator, you are uniquely positioned to assess accountability within the Senate of Canada. The following is a documented record of ethics violations by your current and former Senate colleagues, compiled from public Ethics Officer reports and Senate records.\n\n' +
      'SENATE ETHICS OFFICER FINDINGS \u2014 PUBLIC RECORD:\n\n';

    var knownCases = [
      { name: 'Don Meredith', detail: 'Senate Ethics Officer Inquiry Report 2017: Found to have a sexual relationship with a teenage girl while serving as Senator. Senate Ethics Officer recommended expulsion. Resigned May 2017 before expulsion vote. Source: Senate Ethics Officer Inquiry Report, May 2017.' },
      { name: 'Lynn Beyak', detail: 'Senate Ethics Officer Report 2017\u20132019: Suspended twice. Posted racist letters defending residential schools on her official Senate website. Refused to remove them after direction from Senate Ethics Officer. Retired 2021. Source: Senate Ethics Officer reports.' },
      { name: 'Pamela Wallin', detail: 'Deloitte Audit 2013, Senate Ethics Officer review: $138,969 in improper expenses. Suspended without pay November 2013. Source: Senate of Canada records.' },
      { name: 'Mike Duffy', detail: 'Senate Ethics Officer findings: Residency misrepresentation (appointed as PEI senator while living in Ottawa). $90,172 payment from PM\'s Chief of Staff Nigel Wright to cover expense fraud. Resigned 2015. Charges stayed 2016 but Senate Ethics Officer conduct findings remain public record.' },
      { name: 'Patrick Brazeau', detail: 'Convicted of assault 2014, cocaine possession 2014. Expenses scandal \u2014 suspended without pay 2013. Domestic violence charge. Source: court records, Senate Ethics Officer.' }
    ];

    // Only show cases that are not this senator
    var casesToShow = knownCases.filter(function(c) { return c.name !== contact.name; });
    casesToShow.forEach(function(c) {
      body += c.name + ':\n' + c.detail + '\n\n';
    });

    // If there are other flagged senators from the full dataset
    if (senatorFlagged.length) {
      body += 'ADDITIONAL FLAGGED SENATE RECORDS FROM TENET5 DATABASE:\n\n';
      senatorFlagged.forEach(function(s) {
        if (!casesToShow.some(function(k) { return k.name === s.name; })) {
          body += s.name + ' (' + s.province + '):\n';
          if (s.flags.length) body += 'Flags: ' + s.flags.join(', ') + '\n';
          if (s.notes) body += s.notes + '\n';
          body += '\n';
        }
      });
    }

    body += 'RECOMMENDED ACTION:\n\n' +
      '1. Support independent Senate Ethics Officer with binding investigative authority\n' +
      '2. Support Criminal Code s.122 referrals when Ethics Officer findings demonstrate breach of trust\n' +
      '3. Support Conflict of Interest Act reform: criminal penalties for violations, not just public reprimand\n' +
      '4. Review Senate appointment process to prevent further misconduct\n\n' +
      'EVIDENCE:\n' +
      '  Full investigation findings: ' + BASE_URL + 'findings.html\n' +
      '  Legal framework: ' + BASE_URL + 'legal.html\n' +
      '  Evidence index: ' + BASE_URL + 'evidence-index.html' +
      CLOSING_FOOTER;
  }

  return { subject: subject, body: body, to: contact.email, category: contact.category };
}

// ============================================================
// MEDIA EMAIL
// ============================================================
function generateMediaEmail(contact, allFlaggedPeople) {
  var subject, body;
  var mt = contact.mediaType || 'mainstream';

  if (mt === 'investigative') {
    subject = 'Investigative Lead: Federal Accountability Failures \u2014 Documented Evidence | TENET5';
    body = 'Dear ' + contact.name + ' Editorial Team,\n\n' +
      'I am writing to flag a cluster of interconnected accountability failures documented in official Government of Canada records. Each item below has a specific document citation you can pull directly.\n\n' +
      'LEAD 1: SDTC \u2014 186 CONFLICTS, $400M, CONTEMPT OF PARLIAMENT\n' +
      'Document: Auditor General Report 2024, Chapter [SDTC]. Auditor General found 186 conflicts of interest and ~$400M in questioned grants at Sustainable Development Technology Canada. Ethics Commissioner Report [Verschuren, 2024]: Board Chair voted on grants to her own company NRStor, violating ss.6(1) and 21 of the Conflict of Interest Act. Government held in contempt of Parliament for refusing document production. Case number: Privilege matter, 44th Parliament. Source: oag-bvg.gc.ca, ciec-ccie@parl.gc.ca.\n\n' +
      'LEAD 2: ARRIVACAN \u2014 $60M APP\n' +
      'Document: Auditor General Report 2024. GC Strategies, a 2-person company, received $20.9M in contracts. App estimated at $250K cost $60M. RCMP investigation ongoing. Source: oag-bvg.gc.ca.\n\n' +
      'LEAD 3: LOBBYING CONCENTRATION \u2014 COMMISSIONER\'S RAW CSV\n' +
      'Source: Commissioner of Lobbying raw CSV download: lobbycanada.gc.ca/app/secure/ocl/lrs/do/viewReg\n' +
      '359,251 total communications. PMO: 20,383. Israel-linked organizations: 539 contacts per org (22x China-linked). CIJA alone: 2,156 communications to 993 officials. January 2026 Lobbying Act reforms (8-hour threshold) not enforced. Raw data available for FOIA cross-reference.\n\n' +
      'LEAD 4: CARNEY CONFLICTS \u2014 BROOKFIELD $50B\n' +
      'Documents: Globe and Mail investigative series 2025\u20132026; CBC investigative 2026. PM Carney: 100+ mandatory recusals. Former Brookfield chair. Brookfield pitched $50B fund while he advised the previous PM. 95% of portfolio not covered by ethics screen. Met Brookfield executives after screen imposed (Juno News). G7 summit hosted at Brookfield-managed venue. Source: Ethics Commissioner filings, Globe, CBC.\n\n' +
      'LEAD 5: ARMS EXPORTS \u2014 $229M DESPITE "PAUSE"\n' +
      'Documents: Global Affairs Canada export permits database; Auditor General testimony. $18.9M shipped after Joly\'s "pause" announcement. $37.2M in new permits. Crown corp signed $78.8M contract weeks after blocking the same company. 12 CRA charity revocations for funnelling to military operations abroad.\n\n' +
      'LEAD 6: FOREIGN INTERFERENCE \u2014 NSICOP 2024\n' +
      'Document: NSICOP Report 2024 (Public). Parliamentarians from multiple parties "wittingly" assisting foreign governments. CPC leadership races infiltrated. Han Dong: CSIS assessment as "witting affiliate." Bill C-70 foreign agent registry enforcement inconsistent. Document available: nsicop-cpsnr.ca.\n\n' +
      'LEAD 7: OFFSHORE FINANCIAL ROUTING \u2014 8 MAJOR LEAKS\n' +
      'Documents: ICIJ Offshore Leaks Database; CRA reports; FINTRAC Annual Report 2024. Eight major offshore leaks (LuxLeaks 2014 through Cyprus Confidential 2023) exposed 268,488 entities. 912 Canadian entities in Panama Papers alone. CRA identified $76M unpaid taxes \u2014 zero confirmed collected. PM holds $6.8M in Brookfield options while cutting FINTRAC budget 12% and eliminating 47 analyst positions. Potential s.122 breach of trust. Source: ICIJ, CBC, CRA.\n' +
      '  ' + BASE_URL + 'panama-papers.html\n\n' +
      'LEAD 8: CFNIS STRUCTURAL FAILURE\n' +
      'Documents: MPCC Annual Reports (mpcc-cppm.gc.ca); Federal Court filings. CFNIS reports to same chain it investigates. Investigations ran 3\u20135 years exceeding 12-month standard. Provost Marshal accused of obstruction by MPCC. LCol LeBlanc cleared Gen Vance despite allegations.\n\n' +
      'Full evidence index with document download links:\n' + BASE_URL + 'evidence-index.html\n\n' +
      'All raw data files are public government records available at tenet-5.github.io. Happy to share specific documents, methodology, or raw CSV extracts.' +
      CLOSING_FOOTER;

  } else if (mt === 'mainstream') {
    subject = 'Story Pitch: 5 Major Accountability Failures \u2014 Evidence Available | TENET5';
    body = 'Dear ' + contact.name + ' Editorial Team,\n\n' +
      'Five accountability stories your readers need, each with verified government source documentation:\n\n' +
      '1. THE APP THAT COST $60M\n' +
      'ArriveCAN: estimated at $250K, delivered at $60M. A 2-person company (GC Strategies) received $20.9M. Auditor General confirmed. RCMP investigating. Source: Auditor General Report 2024.\n\n' +
      '2. THE PM WITH 100+ CONFLICTS\n' +
      'PM Carney: 100+ mandatory recusals. Former Brookfield Asset Management chair. Brookfield pitched $50B fund to federal government while Carney advised previous PM. 95% of portfolio unscreened. Caught meeting Brookfield executives after his own screen was imposed. Source: Ethics Commissioner filings, CBC, Globe investigations.\n\n' +
      '3. THE GREEN SLUSH FUND\n' +
      '186 conflicts of interest at Sustainable Development Technology Canada. ~$400M in questioned grants. Board Chair voted on grants to her own company. Government in contempt of Parliament for hiding documents. Source: Auditor General 2024.\n\n' +
      '4. ARMS SALES DESPITE THE PAUSE\n' +
      '$229M+ in arms to Israel despite an official "pause." $18.9M shipped after the pause was announced. Source: Global Affairs Canada permit data.\n\n' +
      '5. LOBBYISTS WHO RULE OTTAWA\n' +
      '359,251 registered lobbying contacts. The PMO alone received 20,383. One foreign-affairs organization averaged 539 contacts per organization \u2014 22x the rate of China-linked organizations. Source: Commissioner of Lobbying raw CSV.\n\n' +
      'Full evidence with source links: ' + BASE_URL + 'findings.html\n' +
      'Evidence index (32 verified files): ' + BASE_URL + 'evidence-index.html' +
      CLOSING_FOOTER;

  } else if (mt === 'right') {
    subject = 'Story Pitch: Fiscal Accountability Data \u2014 ArriveCAN, SDTC, Carney Conflicts | TENET5';
    body = 'Dear ' + contact.name + ' Editorial Team,\n\n' +
      'Verified fiscal accountability data from official government records:\n\n' +
      'ARRIVACAN: $60M FOR A $250K APP\n' +
      'GC Strategies: 2 employees, $20.9M in federal contracts. App used by travellers, budgeted at $250K, delivered at $60M. Auditor General confirmed. RCMP investigating. Source: Auditor General Report 2024.\n\n' +
      'SDTC: $400M QUESTIONED, 186 CONFLICTS\n' +
      'Sustainable Development Technology Canada: 186 documented conflicts of interest. ~$400M in questioned grants. Board Chair voted for grants to her own company. Government held in contempt of Parliament. Source: Auditor General 2024, Ethics Commissioner.\n\n' +
      'PM CARNEY: $50B BROOKFIELD CONFLICT\n' +
      'Mark Carney: former chair, Brookfield Asset Management. Brookfield pitched $50B infrastructure fund to federal government while Carney advised PM Trudeau on economic recovery. 100+ mandatory recusals on file. Ethics screen covers only 5% of his holdings. Met Brookfield executives despite the screen. G7 summit at Brookfield property. BlackRock executive appointed Deputy Minister of Trade. Source: Globe and Mail, CBC, Ethics Commissioner filings 2025\u20132026.\n\n' +
      'LOBBYING CONCENTRATION: TAXPAYER CAPTURE\n' +
      '359,251 registered lobbying communications. PMO: 20,383 contacts from lobbyists. Record 6,223 active registrations November 2024. One sector lobby group averaged 539 contacts per organization. January 2026 Lobbying Act reforms not yet enforced. Source: Commissioner of Lobbying.\n\n' +
      'REVOLVING DOOR\n' +
      'Former Defence Minister now lobbies DND for Raytheon and Israel Aerospace Industries: 408 communications from clients alone. 6+ former Poilievre staffers registered as lobbyists within 18 months. Source: Commissioner of Lobbying raw CSV, The Narwhal.\n\n' +
      'Full fiscal evidence: ' + BASE_URL + 'findings.html\n' +
      'Procurement analysis: ' + BASE_URL + 'procurement-analysis.html\n' +
      'Carney conflicts full dossier: ' + BASE_URL + 'carney-conflicts.html' +
      CLOSING_FOOTER;

  } else if (mt === 'left') {
    subject = 'Story Pitch: Arms Exports, MAID, and Charter Erosion \u2014 Evidence Available | TENET5';
    body = 'Dear ' + contact.name + ' Editorial Team,\n\n' +
      'Three accountability stories with verified government source documentation:\n\n' +
      '$229M ARMS TO ISRAEL \u2014 DESPITE THE PAUSE\n' +
      'Minister Joly announced a "pause" on arms exports to Israel in January 2024. Since that announcement: $18.9M in arms shipped, $37.2M in new export permits issued. A Crown corporation signed a $78.8M contract with a weapons manufacturer weeks after publicly blocking the same company for human rights concerns. 12 CRA charity revocations for funnelling donations to military operations. Source: Global Affairs Canada permit data, Auditor General.\n\n' +
      'MAID EXPANSION: THE INTERNATIONAL OUTLIER\n' +
      'Canada has the highest per-capita Medical Assistance in Dying deaths of any country with MAID legislation. 76,475+ cumulative deaths. 16,499 in 2024 2014 5.1% of all Canadian deaths. Bill C-7 (2021) removed the 10-day reflection period and expanded eligibility to mental illness alone (MAID MD-SUMC). This expansion has no equivalent in any other MAID-legal jurisdiction. Disability rights organizations have raised systemic concerns about socioeconomic drivers. Source: Health Canada Annual Report on Medical Assistance in Dying 2022.\n\n' +
      'BILL C-70: CHARTER CONCERNS IN THE FOREIGN AGENT REGISTRY\n' +
      'Bill C-70\'s foreign agent registry creates new disclosure obligations for organizations receiving foreign direction. Civil liberties groups including CCLA raised concerns about overbreadth and political targeting. Enforcement has been inconsistent \u2014 applied selectively against some organizations while similar activities by others go unregistered. Source: CCLA submissions, NSICOP 2024 report.\n\n' +
      'FOREIGN INTERFERENCE: THE SUPPRESSED REPORT\n' +
      'NSICOP 2024 report found parliamentarians from multiple parties "wittingly" assisted foreign governments. The public version is heavily redacted. Poilievre is the only party leader who refused security clearance to read the full version. Source: NSICOP Report 2024.\n\n' +
      'Full evidence: ' + BASE_URL + 'findings.html\n' +
      'Arms pipeline analysis: ' + BASE_URL + 'arms-pipeline.html\n' +
      'Foreign influence: ' + BASE_URL + 'foreign-influence.html' +
      CLOSING_FOOTER;

  } else if (mt === 'indigenous') {
    subject = 'Story Pitch: Indigenous Community Impacts \u2014 MAID, Interference Evidence | TENET5';
    body = 'Dear ' + contact.name + ' Newsroom,\n\n' +
      'Three documented accountability issues with direct impact on Indigenous communities:\n\n' +
      'MAID AND INDIGENOUS COMMUNITIES\n' +
      'Canada has the highest per-capita MAID deaths of any country with MAID legislation: 76,475+ cumulative. 16,499 in 2024 2014 5.1% of all deaths. Bill C-7 expanded eligibility to mental illness alone (MAID MD-SUMC). Indigenous community organizations and disability rights advocates have documented how poverty, lack of housing, and inadequate health services create conditions where MAID becomes an economic choice rather than a medical one. This is a systemic equity concern the federal government has not addressed. Source: Health Canada Annual Report on Medical Assistance in Dying 2022, Indigenous community submissions to Parliamentary review.\n\n' +
      'RESIDENTIAL SCHOOL LEGACY IN THE SENATE\n' +
      'Senator Lynn Beyak (CPC, retired 2021) posted racist letters defending residential schools on her official Senate website. She was suspended twice by the Senate Ethics Officer. The Senate\'s response \u2014 suspension rather than expulsion \u2014 drew criticism from Indigenous survivors\' organizations. Source: Senate Ethics Officer reports 2017\u20132019.\n\n' +
      'FOREIGN INTERFERENCE AND INDIGENOUS LAND RIGHTS\n' +
      'The NSICOP 2024 report on foreign interference documented influence operations targeting Canadian domestic policy. Environmental organizations that support Indigenous land rights have been targeted by foreign-funded disinformation campaigns designed to discredit land defenders. The bill intended to protect against foreign interference (C-70) also creates new surveillance risks for Indigenous organizations with international Indigenous solidarity connections. Source: NSICOP 2024, CCLA analysis of Bill C-70.\n\n' +
      'Full evidence: ' + BASE_URL + 'findings.html\n' +
      'Foreign influence analysis: ' + BASE_URL + 'foreign-influence.html' +
      CLOSING_FOOTER;
  } else {
    // Fallback
    subject = 'Story Pitch: Federal Accountability Evidence | TENET5';
    body = 'Dear ' + contact.name + ' Editorial Team,\n\n' +
      'Please see the full evidence index at ' + BASE_URL + 'evidence-index.html for documented accountability failures with official government source citations.' +
      CLOSING_FOOTER;
  }

  return { subject: subject, body: body, to: contact.email, category: contact.category };
}

// ============================================================
// THINK TANK EMAIL
// ============================================================
function generateThinkTankEmail(contact, allFlaggedPeople) {
  var subject = 'Policy Evidence Brief: Accountability Infrastructure Failures \u2014 TENET5 OSINT Analysis | TENET5';
  var body = 'Dear ' + contact.name + ' Research Team,\n\n' +
    'I am writing to share a policy evidence brief that may be relevant to your research agenda. This analysis was produced by TENET5 OSINT, an automated intelligence system cross-referencing 7 million records from official Canadian government databases. The findings below document systemic institutional failures that fit the principal-agent and regulatory capture frameworks in public administration literature.\n\n' +
    'PRINCIPAL-AGENT BREAKDOWN: ETHICS ENFORCEMENT\n' +
    'The Conflict of Interest Act represents a classic principal-agent design: Parliament (principal) delegates oversight to the Ethics Commissioner (agent) to discipline Ministers (sub-agents). The system has failed at the enforcement stage. Nine ministers have been found in contravention since 2017; combined monetary penalty: ~$9,391 (one repayment). PM Trudeau violated the Act twice. The Act has no criminal referral mechanism \u2014 findings are issued as public documents with no further consequence. Source: Ethics Commissioner published reports (ciec-ccie@parl.gc.ca).\n\n' +
    'REGULATORY CAPTURE: LOBBYING CONCENTRATION\n' +
    '359,251 registered lobbying communications from the Commissioner of Lobbying raw data. The PMO received 20,383. Record 6,223 active registrations November 2024. A single foreign-affairs organization averaged 539 lobbying contacts per organization \u2014 22x the China-linked sector rate. January 2026 Lobbying Act reforms (8-hour threshold) have not produced measurable enforcement change. This concentration pattern fits the Stigler regulatory capture model: regulated industries have captured the very regulatory framework designed to monitor them. Source: Commissioner of Lobbying raw CSV (lobbycanada.gc.ca).\n\n' +
    'REVOLVING DOOR: DND AND DEFENCE CONTRACTING\n' +
    'Former Defence Minister David Pratt lobbied DND for Raytheon and Israel Aerospace Industries (408 communications from those clients alone). 6+ former Poilievre staffers registered as federal lobbyists within 18 months of leaving his office (The Narwhal). The revolving door literature (Stiglitz, Hellman) predicts that post-employment lobbying concentrations of this kind create persistent policy distortions in procurement and defence contracting. Source: Commissioner of Lobbying, The Narwhal investigative report.\n\n' +
    'AUDIT GOVERNANCE FAILURE: SDTC\n' +
    'The SDTC "Green Slush Fund" case illustrates board governance failure under conditions of weak oversight. 186 conflicts of interest; ~$400M in questioned grants; Board Chair voted on grants to her own company. The Auditor General confirmed violations of ss.6(1) and 21 of the Conflict of Interest Act. The government was held in contempt of Parliament for refusing to produce documents. This is a textbook case of board capture and audit failure. Source: Auditor General Report 2024.\n\n' +
    'OVERSIGHT INDEPENDENCE: CFNIS/MPCC\n' +
    'The Canadian Forces National Investigation Service reports to the same chain of command it investigates \u2014 a structural conflict of interest that the Military Police Complaints Commission has documented repeatedly. MPCC annual reports show investigations exceeding the 12-month standard (some ran 3\u20135 years). The MPCC itself lacks binding authority despite a Federal Court ruling that it can bind military police. This is a clear case of oversight institution design failure. Source: MPCC Annual Reports (mpcc-cppm.gc.ca), Federal Court.\n\n' +
    'OFFSHORE FINANCIAL ENFORCEMENT: INSTITUTIONAL NON-PROSECUTION\n' +
    'Eight major offshore document leaks from LuxLeaks (2014) through Cyprus Confidential (2023) exposed 268,488 entities. 912 Canadian entities in Panama Papers alone. CRA identified $76M in unpaid taxes \u2014 zero confirmed collected. PM holds $6.8M in Brookfield Asset Management options while cutting FINTRAC budget 12% and eliminating 47 analyst positions. This fits the non-prosecution equilibrium model: the system detects violations but structurally cannot or will not enforce. The watchdog is defunded by the entity it monitors. Source: ICIJ Offshore Leaks Database, CRA reports, FINTRAC Annual Report 2024.\n' +
    '  ' + BASE_URL + 'panama-papers.html\n\n' +
    'PROPOSED AREAS FOR POLICY ANALYSIS:\n\n' +
    '1. Criminal penalties as accountability mechanisms: comparative analysis (UK CSBS model vs. Canadian Conflict of Interest Act)\n' +
    '2. Lobbying concentration and democratic equity: quantitative analysis of the January 2026 Lobbying Act reforms\n' +
    '3. Board governance reform at Crown corporations: post-SDTC lessons\n' +
    '4. Military police independence: CFNIS structural reform options\n' +
    '5. PM divestiture requirements: comparative international models\n' +
    '6. Offshore enforcement gap: why 8 major leaks produced zero Canadian criminal prosecutions\n\n' +
    'All source data, methodology, and raw CSV files are available at:\n' +
    '  ' + BASE_URL + 'evidence-index.html\n\n' +
    'This analysis was produced from official government records. We welcome policy collaboration, corrections, or research citation.\n\n' +
    'Evidence index: ' + BASE_URL + 'evidence-index.html\n' +
    'Legal framework analysis: ' + BASE_URL + 'legal.html\n' +
    'Lobbying data: ' + BASE_URL + 'sector-lobbying.html' +
    CLOSING_FOOTER;

  return { subject: subject, body: body, to: contact.email, category: contact.category };
}

// ============================================================
// PREMIER EMAIL
// ============================================================
function generatePremierEmail(contact, allFlaggedPeople) {
  var subject = 'Federal Accountability Data: Constitutional Jurisdiction Concerns | ' + contact.province;
  var peerFlagged = allFlaggedPeople
    ? allFlaggedPeople.filter(function(c) { return c.category === 'premier' && c.name !== contact.name; })
    : [];

  var body = 'Dear ' + contact.name + ',\n\n' +
    'This briefing presents documented federal accountability failures with direct implications for provincial jurisdiction under Constitution Act s.92. This analysis was generated by TENET5 OSINT, an automated intelligence system cross-referencing 7 million records from official Canadian government databases.\n\n' +
    'FEDERAL MAID EXPANSION: PROVINCIAL HEALTH JURISDICTION (s.92(7))\n' +
    'Canada has the highest per-capita MAID deaths of any country with MAID legislation: 76,475+ cumulative deaths. 16,499 in 2024 2014 5.1% of all Canadian deaths. Bill C-7 removed the 10-day reflection period and expanded eligibility to mental illness (MAID MD-SUMC). Under Constitution Act s.92(7), hospitals and health institutions are a provincial matter. Federal MAID expansion creates downstream budget pressure on provincial health systems without commensurate federal funding. Disability rights organizations have raised concerns about socioeconomic drivers that vary by province. Source: Health Canada Annual Report on Medical Assistance in Dying 2022.\n\n' +
    'FEDERAL PROCUREMENT BYPASS: PROVINCIAL ECONOMIC INTEREST\n' +
    'ArriveCAN ($60M for a $250K app) and the SDTC ($400M in questioned grants) represent federal procurement failures that bypassed competitive processes. GC Strategies (2 employees, $20.9M in contracts) was selected without open competition. These concentrated procurement patterns exclude provincial suppliers and small businesses. Source: Auditor General Report 2024.\n\n' +
    'LOBBYING CAPTURE: NATIONAL INTERESTS AT PROVINCIAL EXPENSE\n' +
    '359,251 registered lobbying communications with the federal government. The PMO received 20,383. This concentration means federal policy is heavily influenced by nationally organized lobby groups \u2014 often at the expense of provincial and regional priorities. Oil sector: 10,794 contacts; Banking: 7,497; Pharma: 4,776. Source: Commissioner of Lobbying raw data.\n\n' +
    'FOREIGN INTERFERENCE: PROVINCIAL POLITICAL SYSTEMS\n' +
    'The NSICOP 2024 report documented foreign interference in federal leadership races. Provincial political systems face the same vulnerability without equivalent federal intelligence-sharing frameworks. The Bill C-70 foreign agent registry applies federally but lacks provincial coordination mechanisms. Source: NSICOP Report 2024.\n\n' +
    'SDTC GREEN GRANTS: PROVINCIAL DISTRIBUTION CONCERNS\n' +
    'Sustainable Development Technology Canada distributed ~$400M in questioned grants under 186 conflicts of interest. Provincial innovation companies may have been disadvantaged relative to nationally connected applicants. Source: Auditor General Report 2024.\n\n' +
    'CAF AND PROVINCIAL LABOUR MARKET\n' +
    'Questions about foreign national recruitment into the Canadian Armed Forces, vaccine mandate discharges (~1,500 service members), and CFNIS structural failures affect the federal-provincial relationship on security and labour market policy. Source: MPCC Annual Reports.\n\n' +
    'OFFSHORE FINANCIAL ROUTING: PROVINCIAL TAX BASE EROSION\n' +
    'Eight major offshore leaks (2014-2023) exposed 268,488 entities. CRA identified $76M in unpaid Canadian taxes \u2014 zero confirmed collected. PM holds $6.8M in Brookfield options while cutting FINTRAC budget 12%. Provincial tax revenues are directly eroded when federal offshore enforcement fails \u2014 every dollar hidden offshore is a dollar not flowing through provincial economies. Source: ICIJ Offshore Leaks Database, CRA, FINTRAC Annual Report 2024.\n' +
    '  ' + BASE_URL + 'panama-papers.html\n\n';

  if (peerFlagged.length) {
    body += 'FLAGGED PROVINCIAL GOVERNMENT ISSUES IN OTHER JURISDICTIONS:\n\n';
    peerFlagged.forEach(function(p) {
      body += p.name + ' (' + p.province + ' \u2014 ' + p.role + '):\n';
      if (p.flags.length) body += 'Flags: ' + p.flags.join(', ') + '\n';
      if (p.notes) body += p.notes + '\n';
      body += '\n';
    });
  }

  body += 'RECOMMENDED PROVINCIAL ACTION:\n\n' +
    '1. Formal federal-provincial consultation request on MAID expansion and health budget implications\n' +
    '2. Participation in procurement reform advocacy: open competition requirements for federal contracts\n' +
    '3. Request for federal-provincial intelligence sharing framework re: foreign interference in provincial politics\n' +
    '4. Intergovernmental review of SDTC grant distribution by province\n' +
    '5. Provincial human rights commission review of MAID MD-SUMC implementation\n' +
    '6. Demand federal restoration of FINTRAC capacity to protect provincial tax base from offshore erosion\n\n' +
    'EVIDENCE:\n' +
    '  Full findings: ' + BASE_URL + 'findings.html\n' +
    '  Legal framework: ' + BASE_URL + 'legal.html\n' +
    '  Evidence index: ' + BASE_URL + 'evidence-index.html' +
    CLOSING_FOOTER;

  return { subject: subject, body: body, to: contact.email, category: contact.category };
}

// ============================================================
// COURT / OVERSIGHT EMAIL
// ============================================================
function generateCourtEmail(contact, allFlaggedPeople) {
  var subject = 's.504 Criminal Code \u2014 Information Re: Breach of Trust by Public Officers | TENET5';
  var body = 'To the ' + contact.name + ',\n\n' +
    'This communication provides a formal evidence summary for the purpose of s.504 of the Criminal Code of Canada, which provides that any person may lay an information before a justice of the peace, who shall cause the accused to appear or be brought before the court.\n\n' +
    'LEGAL BASIS FOR INFORMATION:\n\n' +
    '1. CRIMINAL CODE s.122 \u2014 BREACH OF TRUST BY PUBLIC OFFICER\n' +
    'Every official who, in connection with the duties of their office, commits fraud or a breach of trust is guilty of an indictable offence and liable to imprisonment for a term not exceeding five years, whether or not the fraud or breach of trust would be an offence if committed in relation to a private person.\n\n' +
    'PRIMA FACIE EVIDENCE (from Ethics Commissioner published findings):\n\n' +
    'ALLEGATION 1 \u2014 SDTC BOARD: Verschuren et al.\n' +
    'The Ethics Commissioner found that Verschuren voted on grants to her own company NRStor, violating ss.6(1) and 21 of the Conflict of Interest Act. The Auditor General confirmed 186 conflicts of interest and ~$400M in questioned grants. The government was held in contempt of Parliament for refusing to produce documents. This conduct, if it occurred in a private corporate context, would constitute breach of fiduciary duty and potentially fraud (s.380). In a public officer context, s.122 applies directly.\n' +
    'Source document: Ethics Commissioner Report (Verschuren, 2024); Auditor General Report 2024, available at oag-bvg.gc.ca.\n\n' +
    'ALLEGATION 2 \u2014 PM TRUDEAU: Twice found in contravention\n' +
    '2017: PM violated four sections of the Conflict of Interest Act in connection with the Aga Khan vacation. 2019: PM violated s.9 by attempting to direct the Attorney General to intervene in the SNC-Lavalin prosecution. The Ethics Commissioner\'s findings constitute published prima facie evidence. No criminal referral was made.\n' +
    'Source document: Ethics Commissioner Reports (Trudeau I, 2017; Trudeau II, 2019), available at ciec-ccie@parl.gc.ca.\n\n' +
    'ALLEGATION 3 \u2014 MINISTER ETHICS VIOLATIONS (Combined)\n' +
    '9 ministers found in contravention of the Conflict of Interest Act 2017\u20132024. Morneau (daughter at WE Charity during $900M contract), LeBlanc (clam licence to wife\'s cousin), Ng (contracts to personal friend\'s PR firm), Fergus (violated Act as Speaker), Boissonnault (fake Indigenous identity on contract bids, police investigating), Champagne (partner employed at firm receiving $100M+ from his own budget). Combined penalty: ~$9,391.\n' +
    'Source documents: Ethics Commissioner individual reports, available at ciec-ccie@parl.gc.ca.\n\n' +
    '2. CRIMINAL CODE s.121(1)(c) \u2014 CONTRACTOR CORRUPTION\n' +
    'ArriveCAN procurement: GC Strategies (2 employees) received $20.9M in federal contracts without open competition. App estimated at $250K cost $60M. This pattern of direct-award contracting without competition may meet the threshold for s.121(1)(c) (contractor offering or giving a benefit to a government official). RCMP investigation is ongoing.\n' +
    'Source document: Auditor General Report 2024, available at oag-bvg.gc.ca.\n\n' +
    '3. LOBBYING ACT s.14.01 \u2014 PROHIBITED COMMUNICATIONS\n' +
    'January 2026 Lobbying Act reforms created new thresholds for registration and prohibited communications. 359,251 registered lobbying communications are on public record; the PMO received 20,383. The Commissioner of Lobbying has not initiated enforcement proceedings consistent with the 8-hour threshold reform. Formal complaint procedures are available under s.10.4 of the Lobbying Act.\n' +
    'Source document: Commissioner of Lobbying raw CSV (lobbycanada.gc.ca/app/secure/ocl/lrs/do/viewReg).\n\n' +
    'RECOMMENDED LEGAL REMEDIES:\n\n' +
    '1. s.504 information before a justice of the peace: any person may lay an information; the justice shall cause the accused to appear (s.507)\n' +
    '2. Application for a private prosecution under Part XVII of the Criminal Code\n' +
    '3. Formal complaint to the Ethics Commissioner under s.44 of the Conflict of Interest Act\n' +
    '4. Formal complaint to the Commissioner of Lobbying under s.10.4 of the Lobbying Act\n' +
    '5. Application for judicial review in Federal Court (File: Federal Court Registry, Ottawa)\n\n' +
    'All primary source documents are publicly available at:\n' +
    '  Ethics Commissioner: ciec-ccie.parl.gc.ca\n' +
    '  Auditor General: oag-bvg.gc.ca\n' +
    '  Commissioner of Lobbying: lobbycanada.gc.ca\n' +
    '  TENET5 Evidence Index: ' + BASE_URL + 'evidence-index.html\n' +
    '  Legal framework analysis: ' + BASE_URL + 'legal.html\n\n' +
    'This information is provided as a matter of public record in accordance with the open-courts principle and the public interest in accountability for public officers.' +
    CLOSING_FOOTER;

  return { subject: subject, body: body, to: contact.email, category: contact.category };
}

// ============================================================
// MILITARY EMAIL
// ============================================================
function generateMilitaryEmail(contact, allFlaggedPeople) {
  var subject = 'Military Accountability Brief: CFNIS Oversight, Foreign Enlistment, Veterans\u2019 Rights | TENET5';
  var body = 'Dear ' + contact.name + ',\n\n' +
    'This briefing presents documented accountability concerns within the Canadian Armed Forces drawn from Military Police Complaints Commission annual reports, Federal Court filings, and the Commissioner of Lobbying records. This analysis was generated by TENET5 OSINT, an automated intelligence system.\n\n' +
    '1. CFNIS STRUCTURAL CONFLICT OF INTEREST\n' +
    'The Canadian Forces National Investigation Service reports to the same chain of command it investigates. This is a structural conflict of interest that has been documented repeatedly in MPCC annual reports. MPCC has found investigations exceeding the 12-month standard; some ran 3\u20135 years. The Provost Marshal was accused of obstruction by the MPCC \u2014 blocking investigations and redacting evidence. LCol LeBlanc cleared Gen Vance despite documented allegations. Federal Court has ruled the MPCC can bind military police, but enforcement is non-existent. Source: MPCC Annual Reports (mpcc-cppm.gc.ca), Federal Court filings.\n\n' +
    '2. MPCC FINDINGS: SYSTEMIC PATTERN\n' +
    'The Military Police Complaints Commission has documented repeated failures in CFNIS investigations. The pattern \u2014 delayed investigations, evidence redaction, clearing of senior officers despite credible allegations \u2014 constitutes a systemic failure of the military justice system. The MPCC lacks binding authority in practice, despite the Federal Court ruling. This requires legislative reform to give MPCC genuine independence. Source: MPCC Annual Reports.\n\n' +
    '3. ARMS PIPELINE AND DND REVOLVING DOOR\n' +
    'Former Defence Minister David Pratt now lobbies DND for Raytheon and Israel Aerospace Industries: 408 communications from clients alone. $229M+ in arms exports to Israel despite an official "pause." $18.9M shipped after the pause announcement; $37.2M in new permits. A Crown corporation signed a $78.8M contract weeks after publicly blocking the same company. Source: Commissioner of Lobbying raw data, Global Affairs Canada.\n\n' +
    '4. VACCINE MANDATE DISCHARGES\n' +
    'Approximately 1,500 CAF service members were discharged or released for refusing COVID-19 vaccination under orders that were later not renewed. The legal status of those orders and whether the discharges were lawfully conducted remain unresolved. Veterans\' organizations have raised concerns about pension and benefits implications. Source: DND statements, Veterans Ombudsman.\n\n' +
    '5. FOREIGN NATIONAL RECRUITMENT\n' +
    'Questions about the regulatory framework for foreign national recruitment into the Canadian Armed Forces, including eligibility for security clearances, dual-citizenship service members, and NSICOP findings on foreign interference in military institutions. Source: NSICOP 2024, DND.\n\n' +
    '6. VETERANS\u2019 RIGHTS AND OMBUDSMAN REFERRALS\n' +
    'The Veterans Ombudsman has documented systemic gaps in Veterans Affairs Canada service delivery. Discharge process failures, pension processing delays, and mental health service access for veterans discharged under the vaccine mandate require oversight review. Source: Veterans Ombudsman Annual Reports.\n\n' +
    'RECOMMENDED ACTION:\n\n' +
    '1. Legislative reform to establish CFNIS independence from the chain of command\n' +
    '2. Give MPCC binding investigative authority with Federal Court enforcement mechanism\n' +
    '3. Parliamentary review of vaccine mandate discharge status and remediation\n' +
    '4. Lobbying Act enforcement review for post-employment DND lobbying\n' +
    '5. Review of foreign national security clearance policy in CAF context\n\n' +
    'EVIDENCE:\n' +
    '  CFNIS investigation: ' + BASE_URL + 'cfnis.html\n' +
    '  Arms pipeline: ' + BASE_URL + 'arms-pipeline.html\n' +
    '  Legal framework: ' + BASE_URL + 'legal.html\n' +
    '  Evidence index: ' + BASE_URL + 'evidence-index.html' +
    CLOSING_FOOTER;

  return { subject: subject, body: body, to: contact.email, category: contact.category };
}

// ============================================================
// GENERIC FALLBACK
// ============================================================
function generateGenericEmail(contact) {
  var subject = 'Accountability Evidence Brief | TENET5';
  var body = 'Dear ' + contact.name + ',\n\n' +
    'Please see the full evidence index for documented accountability failures with official government source citations:\n\n' +
    '  Evidence Index: ' + BASE_URL + 'evidence-index.html\n' +
    '  Legal framework: ' + BASE_URL + 'legal.html\n' +
    '  About and methodology: ' + BASE_URL + 'about.html' +
    CLOSING_FOOTER;

  return { subject: subject, body: body, to: contact.email, category: contact.category };
}

// ============================================================
// LAW ENFORCEMENT EMAIL (RCMP, Provincial Police, Crown)
// ============================================================
function generateLawEnforcementEmail(contact, allFlaggedPeople) {
  var subject = 'Request for Criminal Investigation — Documented Evidence of Criminal Code Violations by Canadian Public Officers';
  var body = 'Attention: ' + contact.name + '\n' +
    (contact.title ? contact.title + '\n' : '') +
    (contact.institution ? contact.institution + '\n' : '') + '\n' +
    'This correspondence is a formal request to open or expand a criminal investigation based on publicly documented evidence of Criminal Code violations by Canadian public officers.\n\n' +
    'DOCUMENTED CRIMINAL CODE VIOLATIONS:\n\n' +
    '1. BREACH OF TRUST (s.122)\n' +
    'Multiple Ethics Commissioner findings of Conflict of Interest Act violations by sitting and former Cabinet ministers. Combined penalties: ~$9,391 across all cases. Zero criminal referrals despite s.122 carrying up to 5 years imprisonment.\n' +
    '  Evidence: ' + BASE_URL + 'ethics-violations.html\n\n' +
    '2. FRAUD OVER $5,000 (s.380)\n' +
    'ArriveCAN: $60M+ for an application estimated at $250K. GC Strategies (2 employees) received $20.9M. Auditor General: "basic contracting rules broken." 76% of contractor work unsubstantiated. SDTC: 186 conflicts of interest, ~$400M in questioned grants.\n' +
    '  Evidence: ' + BASE_URL + 'arrivecan.html\n\n' +
    '3. CRIMINAL NEGLIGENCE CAUSING DEATH (s.220)\n' +
    '76,475+ MAID deaths since 2016. PBO published cost-savings analysis BEFORE expansion vote. Track 2: 63% cited emotional distress, 53.8% inadequate disability services. 10 provinces demanded pause — government expanded anyway.\n' +
    '  Evidence: ' + BASE_URL + 'maid-accountability.html\n\n' +
    '4. OBSTRUCTION OF JUSTICE (s.139)\n' +
    'Government found in contempt of Parliament (SDTC documents). CFNIS: Ontario Superior Court — "misconduct so egregious it shocks the conscience."\n' +
    '  Evidence: ' + BASE_URL + 'cfnis.html\n\n' +
    '5. OFFSHORE FINANCIAL ROUTING (s.380, s.122)\n' +
    'Eight major document leaks (2014-2023) exposed 268,488 offshore entities. 912 Canadian entities in Panama Papers. CRA identified $76M in unpaid taxes — zero confirmed collected. PM holds $6.8M in Brookfield options while defunding FINTRAC (the offshore monitoring agency) by 12%. Potential s.122 breach of trust and s.380 fraud facilitation.\n' +
    '  Evidence: ' + BASE_URL + 'panama-papers.html\n\n' +
    '6. s.504 PRIVATE PROSECUTION FILED\n' +
    '28 counts submitted to courthouses under s.504 Criminal Code.\n' +
    '  Evidence: ' + BASE_URL + 's504-covey-bae.html\n\n' +
    'REQUEST:\n' +
    'Review the evidence at ' + BASE_URL + 'evidence-index.html and determine whether criminal investigation is warranted.\n\n' +
    '  Evidence index: ' + BASE_URL + 'evidence-index.html\n' +
    '  Legal framework: ' + BASE_URL + 'legal.html\n' +
    '  Investigation matrix: ' + BASE_URL + 'investigation-matrix.html' +
    CLOSING_FOOTER;

  return { subject: subject, body: body, to: contact.email, category: contact.category };
}

// ============================================================
// MP-DIRECT EMAIL (with scorecard + voting record)
// ============================================================
function generateMPEmail(contact, allFlaggedPeople) {
  var mpName = contact.name;
  var riding = contact.riding || contact.province || '';

  var subject = 'Your Accountability Record — ' + mpName + ', MP for ' + riding + ' | TENET5 Evidence Review';
  var body = 'Dear ' + mpName + ',\n' +
    'Member of Parliament for ' + riding + '\n\n' +
    'Your publicly documented record, compiled from Hansard, Commissioner of Lobbying, Health Canada, and Ethics Commissioner:\n\n' +
    '1. MAID VOTING RECORD\n' +
    '76,475+ Canadians died under MAID since 2016 (Health Canada 6th Report). 16,499 in 2024 — 5.1% of all deaths. Your C-14/C-7 votes are in Hansard.\n' +
    '  Your scorecard: ' + BASE_URL + 'search.html?q=' + encodeURIComponent(mpName) + '\n\n' +
    '2. LOBBYING CONTACTS\n' +
    '547,889 registered communications in the Commissioner of Lobbying dataset.\n' +
    '  ' + BASE_URL + 'sector-lobbying.html\n\n' +
    '3. YOUR COLLEAGUES\' ETHICS VIOLATIONS\n' +
    'Nine ministers found in violation. Combined penalties: ~$9,391. Zero criminal referrals.\n' +
    '  ' + BASE_URL + 'ethics-violations.html\n\n' +
    '4. OFFSHORE FINANCIAL EXPOSURE\n' +
    'Eight major offshore leaks (2014-2023) exposed 268,488 entities. $76M in unpaid Canadian taxes identified — zero confirmed collected. PM holds $6.8M in Brookfield options while cutting FINTRAC budget 12%.\n' +
    '  ' + BASE_URL + 'panama-papers.html\n\n' +
    '5. s.504 CRIMINAL CODE FILINGS\n' +
    '28 counts filed at courthouses. As a sitting MP you have the authority to ensure these receive attention.\n' +
    '  ' + BASE_URL + 's504-covey-bae.html\n\n' +
    'ACTION REQUESTED:\n' +
    '1. Review your voting record and its consequences\n' +
    '2. Support s.122 referrals for Ethics Commissioner findings\n' +
    '3. Support Conflict of Interest Act reform with criminal penalties\n' +
    '4. Demand FINTRAC funding restoration and offshore tax enforcement\n\n' +
    '  Full record: ' + BASE_URL + 'investigation-matrix.html\n' +
    '  Evidence: ' + BASE_URL + 'evidence-index.html' +
    CLOSING_FOOTER;

  return { subject: subject, body: body, to: contact.email, category: contact.category };
}

// ============================================================
// COURTHOUSE s.504 COVER LETTER
// ============================================================
function generateCourthouseEmail(contact, allFlaggedPeople) {
  var subject = 'Section 504 Criminal Code — Private Information to Compel Appearance of Accused';
  var body = 'TO THE CLERK OF THE COURT\n' +
    (contact.name ? contact.name + '\n' : '') +
    (contact.institution ? contact.institution + '\n' : '') + '\n' +
    'RE: Private Information under Section 504 of the Criminal Code of Canada\n\n' +
    'INFORMANT: Daniel Perry, Canadian Forces Combat Veteran, Former Signals Operator\n' +
    'DATE: ' + new Date().toISOString().slice(0, 10) + '\n\n' +
    'The enclosed Information alleges offences under the Criminal Code and National Defence Act.\n\n' +
    'CHARGES:\n' +
    '  28 counts against named individuals\n' +
    '  Criminal Code: s.122 (Breach of Trust), s.220 (Criminal Negligence),\n' +
    '    s.380 (Fraud), s.139 (Obstruction)\n' +
    '  National Defence Act: s.83 (Mutiny), s.130 (Prejudicial Conduct)\n\n' +
    'EVIDENCE:\n' +
    '  Evidence index: ' + BASE_URL + 'evidence-index.html\n' +
    '  s.504 filing: ' + BASE_URL + 's504-covey-bae.html\n' +
    '  Legal framework: ' + BASE_URL + 'legal.html\n' +
    '  Investigation: ' + BASE_URL + 'investigation-matrix.html\n\n' +
    'Respectfully requesting this Information be received under s.507.1.\n\n' +
    'Daniel Perry\n' +
    'Canadian Forces Combat Veteran\n' +
    'tenet-5.github.io' +
    CLOSING_FOOTER;

  return { subject: subject, body: body, to: contact.email, category: contact.category };
}
