#!/usr/bin/env python3
# Copyright (c) 2026, TENET5 OSINT Infrastructure
# All rights reserved.
# Authorized LIRIL Execution

import sqlite3
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
import hashlib
import os
import logging
import time
import schedule
import threading

# Set up logging for matrix ledger validation
LOG_FILE = os.path.join(os.path.dirname(__file__), 'court_tracker.log')
logging.basicConfig(
    filename=LOG_FILE, 
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - S504-TRACKER - %(message)s'
)

# Target Courthouse Endpoints (Mocked defaults for safety, injected via env in production)
COURTHOUSE_EMAILS = {
    'Ontario_Superior_Court': os.environ.get('COURT_ON', 'on.courthouse@example.com'),
    'BC_Supreme_Court': os.environ.get('COURT_BC', 'bc.courthouse@example.com'),
    'Alberta_Court_of_King_Bench': os.environ.get('COURT_AB', 'ab.courthouse@example.com'),
    'Quebec_Superior_Court': os.environ.get('COURT_QC', 'qc.courthouse@example.com'),
    'Manitoba_Court_of_King_Bench': os.environ.get('COURT_MB', 'mb.courthouse@example.com')
}

DB_PATH = os.path.join(os.path.dirname(__file__), 's504_court_docket.db')

def create_database():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS submissions
                 (id INTEGER PRIMARY KEY AUTOINCREMENT, 
                  courthouse TEXT, 
                  email TEXT, 
                  hash TEXT, 
                  status TEXT,
                  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP)''')
    conn.commit()
    conn.close()

def log_submission(courthouse, email, file_hash, status):
    """
    Empirical Magic Handoff Memory -> Stores execution safely into SQLite Ledger.
    """
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("INSERT INTO submissions (courthouse, email, hash, status) VALUES (?, ?, ?, ?)", 
              (courthouse, email, file_hash, status))
    conn.commit()
    conn.close()

def send_email(courthouse, email, attachment_path):
    smtp_server = os.environ.get("TENET_SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.environ.get("TENET_SMTP_PORT", 587))
    from_email = os.environ.get("TENET_EMAIL_ACCOUNT", "tenet5.legal@proton.me")
    password = os.environ.get("TENET_EMAIL_PASS", "your-password")

    msg = MIMEMultipart()
    msg['From'] = from_email
    msg['To'] = email
    msg['Subject'] = f'URGENT: s.504 Form 2 Criminal Notification - {courthouse}'

    body = (
        "To the Honorable Justice of the Peace / Registrar:\n\n"
        "Please find attached the s.504 Form 2 criminal notification (Information) generated "
        "by the TENET5 OSINT Infrastructure regarding systemic institutional offenses.\n\n"
        "As per s.504 of the Criminal Code of Canada, a justice who receives an information "
        "has a mandatory duty to receive it.\n\n"
        "Attached: Form2_Section504_Template.pdf\n"
    )
    msg.attach(MIMEText(body, 'plain'))

    filename = os.path.basename(attachment_path)
    with open(attachment_path, 'rb') as attachment:
        part = MIMEBase('application', 'octet-stream')
        part.set_payload(attachment.read())
        
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', f"attachment; filename= {filename}")
    msg.attach(part)

    try:
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(msg['From'], password)
        server.sendmail(msg['From'], msg['To'], msg.as_string())
        server.quit()
    except Exception as e:
        raise RuntimeError(f"SMTP Transmission Failed: {e}")

def calculate_hash(filepath):
    """ Hydrogen-compliance cryptographic signing of the dossier """
    with open(filepath, 'rb') as f:
        return hashlib.sha256(f.read()).hexdigest()

def main():
    print(f"[TENET5] Initializing S.504 Court Tracking Protocol at {time.strftime('%X')}")
    create_database()
    
    # Locate the PDF template generated by form2_504.py
    attachment = os.path.join(os.path.dirname(__file__), '..', '..', 'S.L.A.T.E', 'tenet5', 'Form2_Section504_Template.pdf')
    
    if not os.path.exists(attachment):
        # Fallback to local if passed directly
        attachment = os.path.join(os.path.dirname(__file__), 'Form2_Section504_Template.pdf')
        if not os.path.exists(attachment):
            print(f"[ERROR] Target dossier {attachment} not found.")
            logging.error("Target s.504 dossier PDF not found.")
            return

    file_hash = calculate_hash(attachment)
    print(f"  [+] Dossier loaded. SHA256 Signature: {file_hash[:16]}...")

    for courthouse, email in COURTHOUSE_EMAILS.items():
        try:
            print(f"  [>] Dispatching to {courthouse} ({email})...")
            send_email(courthouse, email, attachment)
            log_submission(courthouse, email, file_hash, 'Success')
            logging.info(f"Successfully filed to {courthouse} | Hash: {file_hash}")
            print(f"  [✓] Success.")
        except Exception as e:
            log_submission(courthouse, email, file_hash, 'Failure')
            logging.error(f"Failed filing to {courthouse} ({email}): {str(e)}")
            print(f"  [✗] Failed: {str(e)}")

def run_schedule():
    # Execute autonomous filing every 24 hours to ensure continuous accountability
    schedule.every(24).hours.do(main)

    while True:
        schedule.run_pending()
        time.sleep(60)

if __name__ == '__main__':
    print("[ACTIVE] LIRIL s.504 Court Tracker (Daemon Mode)")
    # Initial trigger
    main()
    
    # Initialize scheduling
    thread = threading.Thread(target=run_schedule)
    thread.daemon = True
    thread.start()
    
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\n[STOP] Court Tracker Terminated.")
