import json
import os
import sqlite3

BOARD_FILE = r"e:\TENET-5.github.io\data\investigation_board.js"
DB_PATH = r"e:\S.L.A.T.E\tenet5\.liril_discoveries.db"

def extract_liril_discoveries():
    """Extract ABCXYZ protected Millennial Falcon discoveries from the LIRIL Matrix."""
    if not os.path.exists(DB_PATH):
        print(f"ERROR: Local LIRIL matrix DB not found at {DB_PATH}")
        return []

    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    # Pull protected ABCXYZ findings generated by np_millennial_falcon.py
    try:
        c.execute("SELECT discovery_value, crypto_signature FROM falcon_discoveries WHERE discovery_key = 'ABCXYZ'")
        rows = c.fetchall()
    except sqlite3.OperationalError:
        print("FALCON DISCOVERIES table uninitialized in LIRIL SQL. Returning empty.")
        rows = []
    conn.close()
    
    nodes = []
    for row in rows:
        try:
            data = json.loads(row[0])
            sig = row[1]
            complexity = data.get("matrix_complexity", "P-CLASS")
            name = data.get("name", "Unknown Node")
            
            # Format nicely for the DAG
            n_id = sig[:8].lower()
            nodes.append({
                "id": f"falcon_{n_id}",
                "type": "organization" if "influence" in name.lower() else "event",
                "label": name.replace("_", " ").title(),
                "subtitle": f"Complexity: {complexity}",
                "detail": f"Vector: {data.get('topological_vector', 'N/A')}. ABCXYZ LIRIL Handoff Sec: {sig}",
                "link": "index.html",
                "categories": ["evidence", "temporal_anomaly"] if "CHRONOS" in complexity else ["evidence"],
                "x": 50,
                "y": 50,
                "falcon_data": data
            })
        except json.JSONDecodeError:
            continue
    return nodes

with open(BOARD_FILE, "r", encoding="utf-8") as f:
    content = f.read()

json_str = content.replace("window.BOARD_DATA = ", "").strip()
if json_str.endswith(";"):
    json_str = json_str[:-1]

data = json.loads(json_str)

# Integrate dynamic ABCXYZ findings
new_nodes = extract_liril_discoveries()

existing_ids = {n["id"] for n in data["nodes"]}
for n in new_nodes:
    if n["id"] not in existing_ids:
        # Avoid clustering all new nodes directly in the center
        n["x"] = 25 + (len(existing_ids) * 5) % 50
        n["y"] = 25 + (len(existing_ids) * 3) % 50
        data["nodes"].append(n)

# Dynamically link new falcon nodes back to a central node (e.g., 'foreign_alpha' or internal 'liril_core')
new_threads = []
for n in new_nodes:
    if n["id"] not in existing_ids:
        new_threads.append({
            "from": "cfnis_proxy", # Central nexus
            "to": n["id"],
            "label": "MF_CONVERGENCE",
            "strength": 4
        })

for t in new_threads:
    if not any(et["from"] == t["from"] and et["to"] == t["to"] for et in data["threads"]):
        data["threads"].append(t)

new_content = "window.BOARD_DATA = " + json.dumps(data, indent=2) + ";"
with open(BOARD_FILE, "w", encoding="utf-8") as f:
    f.write(new_content)

# Update the json equivalent as well for offline integrity
with open(BOARD_FILE.replace(".js", ".json"), "w", encoding="utf-8") as f:
    f.write(json.dumps(data, indent=2))

print(f"SUCCESS: Injected {len([n for n in new_nodes if n['id'] not in existing_ids])} LIRIL Millennial Falcon discoveries to investigation_board.js")
